name: Bug Report
description: File a bug report
title: "🐛 "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you start

        - Check for plugin updates and make sure you're running the latest version of the plugin.
        - Restart Obsidian and see if the issue persists.
        - Look at existing bug reports to see if your issue has already been reported.
        - Is this actually a bug? If this is something that you wish the plugin could do, please submit a feature request instead.

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Current behaviour
      description: |
        Describe what actually happened.

        Be specific about the actions you took.
        Screenshots or short recordings help, especially if the issue is visual.
    validations:
      required: true

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which Operating Systems are you using?
      description: You may select more than one.
      options:
        - label: Android
        - label: iPhone/iPad
        - label: Linux
        - label: macOS
        - label: Windows

  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian Version
      description: Which Obsidian version are you using?
      placeholder: 1.9.0
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Which plugin version are you using?
      placeholder: 0.1.0
    validations:
      required: true

  - type: checkboxes
    id: other-plugins-disabled
    attributes:
      label: Checks
      description: Please confirm
      options:
        - label: I have tried it in the sandbox vault with only this plugin enabled
          required: false

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: |
        Not obligatory, but please suggest a fix or reason for the bug, if you have an idea.
